name: Gitea Auto Deploy
run-name: Gitea Auto Deploy

# 在main分支发生push事件时触发。
on:
  push:
    branches:
      - main

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

defaults:
  run:
    shell: powershell

jobs:
  build:
    runs-on: windows
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ${{ gitea.DEPLOY_SCIRPT }}
