name: deploy

# 在main分支发生push事件时触发。
on:
  push:
    branches:
      - master

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build:
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    steps:
      # 检出
      - name: Checkout
        uses: actions/checkout@v2

        # 安装 node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          # cache: "yarn"

        # 构建
      - name: Build
        run: |
          yarn install
          yarn build

      # - name: FTP deploy
      #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./dist/
      #     server-dir: ${{ secrets.FTP_SERVER_DIR }}

      # - name: ssh deploy
      #   uses: easingthemes/ssh-deploy@main
      #   with:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ARGS: '-avzr --delete'
      #     SOURCE: './dist/'
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.REMOTE_TARGET }}

      - name: copy file via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          # password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './dist/'
          target: ${{ secrets.REMOTE_TARGET }}
          # windowsserver自带的tar不支持--overwrite
          # overwrite: true
          # rm: true # 只能每次删了，暂时这样处理

        # 同步到又拍云
      # - name: Deploy upyun
      #   run: |
      #     wget -O upx.tar.gz http://collection.b0.upaiyun.com/softwares/upx/upx_0.3.6_linux_x86_64.tar.gz
      #     tar -zxf upx.tar.gz
      #     chmod +x upx
      #     ./upx login ${{ secrets.UP_BUCKET }} ${{ secrets.UP_OPERATOR }} ${{ secrets.UP_OPERATOR_PASSWORD }}
      #     ./upx sync dist/ / --delete
      #     ./upx logout

      # 发布到 gh-page 分支
      # - name: Deploy github
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     publish_dir: ./dist
      #     deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      #     user_name: "github-actions[bot]"
      #     user_email: "github-actions[bot]@users.noreply.github.com"
